#' Generate a customized oncoplot with clinical tracks
#'
#' @param maf A MAF object generated by read.maf
#' @param genes Number of top genes to plot, default 20
#' @param clinical_data Data frame containing clinical information
#' @param clinical_vars List defining variables and their types (discrete/continuous)
#' @return A patchwork/aplot object
#' @import ggplot2
#' @importFrom patchwork plot_layout wrap_plots
#' @importFrom ggplotify as.ggplot
#' @importFrom aplot insert_top insert_right insert_bottom
#' @export
oncoplot <- function(maf, genes = 20, clinical_data = NULL, clinical_vars = NULL) {
  # 内部组件调用
  p_main <- oncoplot_main(maf, genes)
  p_top <- aplotExtra:::oncoplot_sample(maf, genes)
  p_right <- aplotExtra:::oncoplot_gene(maf, genes, ylab = 'percentage')
  p_legend <- oncoplot_legend(maf, genes)
  p_spacer <- ggplot() + ggfun::theme_transparent()

  # 组装基础架构
  pp <- aplot::insert_top(p_main, p_spacer, height = 0.03) |>
    aplot::insert_top(p_top, height = 0.2) |>
    aplot::insert_right(p_spacer, width = 0.01) |>
    aplot::insert_right(p_right, width = 0.2)

  all_legends <- list()

  # 临床信息轨道处理
  if (!is.null(clinical_data) && !is.null(clinical_vars)) {
    # 规范化列名
    colnames(clinical_data)[1] <- "Tumor_Sample_Barcode"

    for (var in names(clinical_vars)) {
      if (var %in% colnames(clinical_data)) {
        p_track <- oncoplot_clinical_track(maf, clinical_data, var, clinical_vars[[var]], genes)
        leg_obj <- ggfun::get_legend(p_track)
        all_legends[[length(all_legends) + 1]] <- ggplotify::as.ggplot(leg_obj)
        pp <- aplot::insert_bottom(pp, p_track + theme(legend.position = "none"), height = 0.04)
      }
    }
  }

  # 转换并添加图例
  pp_final <- ggplotify::as.ggplot(pp) + p_legend +
    patchwork::plot_layout(widths = c(10, 1.5))

  if (length(all_legends) > 0) {
    legend_column <- patchwork::wrap_plots(all_legends, ncol = 1) +
      patchwork::plot_layout(guides = "collect") &
      theme(plot.margin = margin(l = 5, r = 5, t = 10, b = 10))

    pp_out <- (ggplotify::as.ggplot(pp_final) | legend_column) +
      patchwork::plot_layout(widths = c(10, 2))
  } else {
    pp_out <- pp_final
  }

  class(pp_out) <- c("oncoplot_result", class(pp_out))
  return(pp_out)
}

#' @keywords internal
oncoplot_main <- function(maf, genes = 20) {
  d <- aplotExtra:::oncoplot_tidy_onco_matrix(maf, genes)

  ggplot(d, aes(x = .data$Sample, y = .data$Gene, fill = .data$Type)) +
    geom_tile(colour = "white", linewidth = 0.01) +
    aplotExtra:::oncoplot_setting(continuous = FALSE) +
    theme(
      legend.position = "none",
      axis.text.y.left = element_text(face = 'italic'),
      plot.margin = margin(t = 5, r = 2, b = 0, l = 5)
    )
}

#' @keywords internal
oncoplot_legend <- function(maf, genes = 20) {
  vc_summary <- aplotExtra:::obtain.sample.summary.MAF(maf)
  present_types <- colnames(vc_summary)[c(-1, -ncol(vc_summary))]
  df <- data.frame(Type = present_types, Value = 1)

  p <- ggplot(df, aes(x = Value, y = Value, fill = Type)) +
    geom_tile() +
    aplotExtra:::oncoplot_fill(name = "Mutation Type") +
    theme_void() +
    theme(
      legend.position = "right",
      legend.title = element_text(size = 10, face = "bold"),
      legend.text = element_text(size = 9)
    ) +
    guides(fill = guide_legend(ncol = 1, title = "Mutation Type"))

  leg <- ggfun::get_legend(p)
  ggplotify::as.ggplot(leg) + theme(plot.margin = margin(l = 5, r = 5))
}

#' @keywords internal
oncoplot_clinical_track <- function(maf, clinical_data, var_name,
                                    type = c("discrete", "continuous"),
                                    genes = 20, colors = NULL) {
  type <- match.arg(type)
  onco_matrix <- aplotExtra:::oncoplot_tidy_onco_matrix(maf, genes)
  sample_order <- unique(as.character(onco_matrix$Sample))

  df <- clinical_data[, c("Tumor_Sample_Barcode", var_name)]
  df$Tumor_Sample_Barcode <- factor(df$Tumor_Sample_Barcode, levels = sample_order)

  if (type == "continuous") {
    df[[var_name]] <- cut(df[[var_name]], breaks = 5, include.lowest = TRUE)
  } else {
    df[[var_name]] <- as.factor(df[[var_name]])
  }

  p <- ggplot(df, aes(x = .data$Tumor_Sample_Barcode, y = var_name, fill = .data[[var_name]])) +
    geom_tile(color = "white", linewidth = 0.1) +
    theme_void() +
    coord_cartesian(expand = FALSE)

  if (!is.null(colors)) {
    p <- p + scale_fill_manual(values = colors, name = var_name, na.value = "grey90")
  }

  p + theme(
    axis.text.y = element_text(size = 10, color = "black", hjust = 1, margin = margin(r = 5)),
    legend.position = "right"
  )
}
